server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = / {
    try_files /index.html =404;
  }

  location ~ ^/aluno[0-9]{2}$ {
    return 301 $uri/;
  }

  location ~ ^/aluno[0-9]{2}/$ {
    try_files /labs$uri /labs$uri/index.html =404;
  }

  location /api/ {
    proxy_pass http://provisioner:9002/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location /r1/ {
    proxy_pass http://ttyd-r1:7681/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
  }

  location /r2/ {
    proxy_pass http://ttyd-r2:7682/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
  }

  location /r3/ {
    proxy_pass http://ttyd-r3:7683/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
  }

  location /r4/ {
    proxy_pass http://ttyd-r4:7684/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
  }

  include /etc/nginx/conf.d/labs/*.conf;
}
